apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: letsencrypt2-deployment
  labels:
    app: letsencrypt2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: letsencrypt2
  template:
    metadata:
      labels:
        app: letsencrypt2
    spec:
      containers:
      - name: letsencrypt-https
        image: eu.gcr.io/$PROJECT/letsencrypt2
        ports:
        - containerPort: 80
        - containerPort: 443
---
apiVersion: v1
kind: Service
metadata:
  name: service-letsencrypt2
spec:
  ports:
  - name: http
    port: 80
    targetPort: 80
  - name: https
    port: 443
    targetPort: 443
  selector:
    app: letsencrypt2
  type: LoadBalancer